In [3]:
# random 주사위

In [6]:
import random as r
# ran = int(r.random() *6 +1)

box = []        #초기화

In [20]:
ran = r.randint(1,10)
box.append(ran)
print(box,len(box))

[3, 5, 6, 4, 6, 4, 4, 8, 9, 4] 10

In [101]:
import random as r
# ran = int(r.random() *6 +1)
box = []   
to = 225975
num = 0
while num < to :
    num = num + 1
    ran = r.randint(1,6)
    box.append(ran)
print(len(box),'\n')

print('1은', box.count(1),'번 나왔습니다',"%0.2f" % (box.count(1)/to*100)+'%')
print('2는', box.count(2),'번 나왔습니다',"%0.2f" % (box.count(2)/to*100)+'%')
print('3은', box.count(3),'번 나왔습니다',"%0.2f" % (box.count(3)/to*100)+'%')
print('4는', box.count(4),'번 나왔습니다',"%0.2f" % (box.count(4)/to*100)+'%')
print('5는', box.count(5),'번 나왔습니다',"%0.2f" % (box.count(5)/to*100)+'%')
print('6은', box.count(6),'번 나왔습니다',"%0.2f" % (box.count(6)/to*100)+'%','\n')

x = max(box.count(1),box.count(2),box.count(3),box.count(4),box.count(5),box.count(6))
y = min(box.count(1),box.count(2),box.count(3),box.count(4),box.count(5),box.count(6))

if x == box.count(1):
    print('1이 제일 많이 나왔습니다.')
elif x == box.count(2) :
    print('2가 제일 많이 나왔습니다.')
elif x == box.count(3) :
    print('3이 제일 많이 나왔습니다.')
elif x == box.count(4) :
    print('4가 제일 많이 나왔습니다.')
elif x == box.count(5) :
    print('5가 제일 많이 나왔습니다.')
else :
    print('6이 제일 많이 나왔습니다.')


if y == box.count(1):
    print('1이 제일 적게 나왔습니다.')
elif y == box.count(2) :
    print('2가 제일 적게 나왔습니다.')
elif y == box.count(3) :
    print('3이 제일 적게 나왔습니다.')
elif y == box.count(4) :
    print('4가 제일 적게 나왔습니다.')
elif y == box.count(5) :
    print('5가 제일 적게 나왔습니다.')
else :
    print('6이 제일 적게 나왔습니다.')

225975

1은 37422 번 나왔습니다 16.56%
2는 37838 번 나왔습니다 16.74%
3은 37711 번 나왔습니다 16.69%
4는 37509 번 나왔습니다 16.60%
5는 37726 번 나왔습니다 16.69%
6은 37769 번 나왔습니다 16.71%

2가 제일 많이 나왔습니다.
1이 제일 적게 나왔습니다.

In [10]:
dir(r)

['BPF',
 'LOG4',
 'NV_MAGICCONST',
 'RECIP_BPF',
 'Random',
 'SG_MAGICCONST',
 'SystemRandom',
 'TWOPI',
 '_ONE',
 '_Sequence',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_accumulate',
 '_acos',
 '_bisect',
 '_ceil',
 '_cos',
 '_e',
 '_exp',
 '_fabs',
 '_floor',
 '_index',
 '_inst',
 '_isfinite',
 '_lgamma',
 '_log',
 '_log2',
 '_os',
 '_parse_args',
 '_pi',
 '_random',
 '_repeat',
 '_sha512',
 '_sin',
 '_sqrt',
 '_test',
 '_test_generator',
 '_urandom',
 'betavariate',
 'binomialvariate',
 'choice',
 'choices',
 'expovariate',
 'gammavariate',
 'gauss',
 'getrandbits',
 'getstate',
 'lognormvariate',
 'main',
 'normalvariate',
 'paretovariate',
 'randbytes',
 'randint',
 'random',
 'randrange',
 'sample',
 'seed',
 'setstate',
 'shuffle',
 'triangular',
 'uniform',
 'vonmisesvariate',
 'weibullvariate']

In [2]:
coffee = 0
money = 300
while money:
    (print('300원을 받았으니 커피를 줍니다'))
    coffee = coffee +1
    print('판매한 커피 갯수는 %d개 입니다'%coffee)
    if coffee == 10 :
        print('커피 매진. 판매 중지')
        break

300원을 받았으니 커피를 줍니다
판매한 커피 갯수는 1개 입니다
300원을 받았으니 커피를 줍니다
판매한 커피 갯수는 2개 입니다
300원을 받았으니 커피를 줍니다
판매한 커피 갯수는 3개 입니다
300원을 받았으니 커피를 줍니다
판매한 커피 갯수는 4개 입니다
300원을 받았으니 커피를 줍니다
판매한 커피 갯수는 5개 입니다
300원을 받았으니 커피를 줍니다
판매한 커피 갯수는 6개 입니다
300원을 받았으니 커피를 줍니다
판매한 커피 갯수는 7개 입니다
300원을 받았으니 커피를 줍니다
판매한 커피 갯수는 8개 입니다
300원을 받았으니 커피를 줍니다
판매한 커피 갯수는 9개 입니다
300원을 받았으니 커피를 줍니다
판매한 커피 갯수는 10개 입니다
커피 매진. 판매 중지

# for 문

In [68]:
test_list = ['one', 'two', 'three']
for i in test_list:
    print(i)

one
two
three

In [72]:
# 다양한 for문의 사용
(A,B) = (1,2)

In [73]:
a= [(1,2,11),(3,4,33),(5,6,55)]
for (x,y,z) in a:
    print(x,y,z)

1 2 11
3 4 33
5 6 55

In [79]:
marks = [90,25,67,45,80]

number = 0
for mark in marks :
    number = number +1
    if mark < 60:
        continue
    print('%d번 학생 축하합니다 합격입니다' %number)

1번 학생 축하합니다 합격입니다
3번 학생 축하합니다 합격입니다
5번 학생 축하합니다 합격입니다

In [83]:
marks = [1,2,3,4,5,6,7,8,9,10]

number = 0
for mark in marks :
    number = number +1
    if number%2 == 0 :
        continue
    print('%d 홀수' %number)

1 홀수
3 홀수
5 홀수
7 홀수
9 홀수

In [102]:
# range

a = range(10)
print(a)

range(0, 10)

In [103]:
for n in range(10,50,2) :
    print(n)

10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48

In [105]:
print(list(range(10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [107]:
for even in range(0,10,2):
    print(even)

0
2
4
6
8

In [109]:
for odd in range(1,11,2) :
    print(odd)

1
3
5
7
9

In [121]:
a = 0
for n in range(0,101,1) :
    a += n
print(a)

5050

In [123]:
ma = [90,25,67,45,80]
for number in range(len(ma)):
    if ma[number] < 60:
        continue
    print('%d 학생 축하합니다 합격입니다' %(number +1))

1 학생 축하합니다 합격입니다
3 학생 축하합니다 합격입니다
5 학생 축하합니다 합격입니다

In [4]:
#연습

import calendar
c = calendar.TextCalendar(calendar.SUNDAY)
print(c.formatmonth(2025,2))

   February 2025
Su Mo Tu We Th Fr Sa
                   1
 2  3  4  5  6  7  8
 9 10 11 12 13 14 15
16 17 18 19 20 21 22
23 24 25 26 27 28

In [6]:
# 테스트 타이머

import time as t
for x in range (20) :
    print(f'♬', end='')
    t.sleep(1)

♬♬♬♬♬♬♬♬♬♬♬♬♬♬♬♬

KeyboardInterrupt:

In [31]:
# 리스트 속도 측정
import time as t
lt = []
tp = []
length = 1000
for x in range(length):
    lt.append(x)
for t in range(length) :
    tp.append(t) 
tp = tuple (tp)
print(lt,type(lt))
print(tp,type(tp))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662, 663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701, 702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714, 715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727, 728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740, 741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753, 754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766, 767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779, 780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792, 793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805, 806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818, 819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831, 832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844, 845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857, 858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870, 871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883, 884, 885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 895, 896, 897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909, 910, 911, 912, 913, 914, 915, 916, 917, 918, 919, 920, 921, 922, 923, 924, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935, 936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948, 949, 950, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961, 962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974, 975, 976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987, 988, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999] <class 'list'>
(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662, 663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701, 702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714, 715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727, 728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740, 741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753, 754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766, 767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779, 780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792, 793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805, 806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818, 819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831, 832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844, 845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857, 858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870, 871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883, 884, 885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 895, 896, 897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909, 910, 911, 912, 913, 914, 915, 916, 917, 918, 919, 920, 921, 922, 923, 924, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935, 936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948, 949, 950, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961, 962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974, 975, 976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987, 988, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999) <class 'tuple'>

In [33]:
import time
start = time.time()
for x in lt:
    a = 1

print(time.time() - start)

0.0001785755157470703

In [36]:
import time
start = time.time()
for x in tp:
    tps = (1,2,3,4,5)

print(time.time() - start)

0.00017261505126953125

In [1]:
!pip install tqdm

Requirement already satisfied: tqdm in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (4.67.1)
Requirement already satisfied: colorama in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from tqdm) (0.4.6)

In [3]:
from tqdm import tqdm
import time as tt
for x in tqdm(range(100)):
    pass
    tt.sleep(0.1)

100%|████████████████████████████████████████████████████████████████████████████████| 100/100 [00:10<00:00,  9.75it/s]

In [19]:
# 비트코인 시세로 상승장 하강장 구분하기
import requests as req
url = "https://api.bithumb.com/public/ticker/ALL_KRw"
gdata = req.get(url).json()
btc = (gdata['data']['BTC'])
maxp =float (btc['max_price'])
minp =float (btc['max_price'])
openp = float(btc['max_price'])
bandp = float(maxp) - float(minp)

if(openp + bandp) > maxp :
    print('상승장')
else :
    print('하강장')

하강장

In [20]:
import requests as req
url = "https://api.bithumb.com/v1/candles/minutes/1?market=KRW-BTC&count=1"
btc_data = req.get(url).json()
print(btc_data[0]['trade_price'])

149945000

In [27]:
for i in range(1,10) :
    print(f'{2} * {i} = {2}*i')

2 * 1 = 2*i
2 * 2 = 2*i
2 * 3 = 2*i
2 * 4 = 2*i
2 * 5 = 2*i
2 * 6 = 2*i
2 * 7 = 2*i
2 * 8 = 2*i
2 * 9 = 2*i

In [80]:
for i in range(2,10) :
    print(f'{i}단')
    for j in range(1,10):
        print(f'{i} * {j} = {i*j}')
    print(f'{i} 단 종료','\n')

2단
2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10
2 * 6 = 12
2 * 7 = 14
2 * 8 = 16
2 * 9 = 18
2 단 종료

3단
3 * 1 = 3
3 * 2 = 6
3 * 3 = 9
3 * 4 = 12
3 * 5 = 15
3 * 6 = 18
3 * 7 = 21
3 * 8 = 24
3 * 9 = 27
3 단 종료

4단
4 * 1 = 4
4 * 2 = 8
4 * 3 = 12
4 * 4 = 16
4 * 5 = 20
4 * 6 = 24
4 * 7 = 28
4 * 8 = 32
4 * 9 = 36
4 단 종료

5단
5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
5 단 종료

6단
6 * 1 = 6
6 * 2 = 12
6 * 3 = 18
6 * 4 = 24
6 * 5 = 30
6 * 6 = 36
6 * 7 = 42
6 * 8 = 48
6 * 9 = 54
6 단 종료

7단
7 * 1 = 7
7 * 2 = 14
7 * 3 = 21
7 * 4 = 28
7 * 5 = 35
7 * 6 = 42
7 * 7 = 49
7 * 8 = 56
7 * 9 = 63
7 단 종료

8단
8 * 1 = 8
8 * 2 = 16
8 * 3 = 24
8 * 4 = 32
8 * 5 = 40
8 * 6 = 48
8 * 7 = 56
8 * 8 = 64
8 * 9 = 72
8 단 종료

9단
9 * 1 = 9
9 * 2 = 18
9 * 3 = 27
9 * 4 = 36
9 * 5 = 45
9 * 6 = 54
9 * 7 = 63
9 * 8 = 72
9 * 9 = 81
9 단 종료

In [72]:
for i in range(2,10) :
    for j in range(1,10):
        print(i*j,end=" ")
    print(' ')

2 4 6 8 10 12 14 16 18
3 6 9 12 15 18 21 24 27
4 8 12 16 20 24 28 32 36
5 10 15 20 25 30 35 40 45
6 12 18 24 30 36 42 48 54
7 14 21 28 35 42 49 56 63
8 16 24 32 40 48 56 64 72
9 18 27 36 45 54 63 72 81

# 리스트 컴프리헨션

In [82]:
a = [1,2,3,4]
result = []
for num in a:
    result.append(num*3)
print(result)

[3, 6, 9, 12]

In [83]:
[num*3 for num in [1,2,3,4]]

[3, 6, 9, 12]

In [84]:
#테스트1
#list (range(10))
[x for x in range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [85]:
res = []
for x in range (10):
    if x%2==0:
        res.append(x)
print(res)

[0, 2, 4, 6, 8]

In [86]:
[x for x in range(10) if x%2==0]

[0, 2, 4, 6, 8]

In [89]:
result = [ i*j for i in range(2,10) for j in range(1,10)]
print(result)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 3, 6, 9, 12, 15, 18, 21, 24, 27, 4, 8, 12, 16, 20, 24, 28, 32, 36, 5, 10, 15, 20, 25, 30, 35, 40, 45, 6, 12, 18, 24, 30, 36, 42, 48, 54, 7, 14, 21, 28, 35, 42, 49, 56, 63, 8, 16, 24, 32, 40, 48, 56, 64, 72, 9, 18, 27, 36, 45, 54, 63, 72, 81]

In [90]:
for a in [f'{j}x{i} = {j*i}' for j in range(2,10) for i in range(1,10)] :
    print(a)

2x1 = 2
2x2 = 4
2x3 = 6
2x4 = 8
2x5 = 10
2x6 = 12
2x7 = 14
2x8 = 16
2x9 = 18
3x1 = 3
3x2 = 6
3x3 = 9
3x4 = 12
3x5 = 15
3x6 = 18
3x7 = 21
3x8 = 24
3x9 = 27
4x1 = 4
4x2 = 8
4x3 = 12
4x4 = 16
4x5 = 20
4x6 = 24
4x7 = 28
4x8 = 32
4x9 = 36
5x1 = 5
5x2 = 10
5x3 = 15
5x4 = 20
5x5 = 25
5x6 = 30
5x7 = 35
5x8 = 40
5x9 = 45
6x1 = 6
6x2 = 12
6x3 = 18
6x4 = 24
6x5 = 30
6x6 = 36
6x7 = 42
6x8 = 48
6x9 = 54
7x1 = 7
7x2 = 14
7x3 = 21
7x4 = 28
7x5 = 35
7x6 = 42
7x7 = 49
7x8 = 56
7x9 = 63
8x1 = 8
8x2 = 16
8x3 = 24
8x4 = 32
8x5 = 40
8x6 = 48
8x7 = 56
8x8 = 64
8x9 = 72
9x1 = 9
9x2 = 18
9x3 = 27
9x4 = 36
9x5 = 45
9x6 = 54
9x7 = 63
9x8 = 72
9x9 = 81